#!/bin/bash

###############################################################################
# SHASK                                                                       #
#                                                                             #
# A simple Bash utility to log questions.                                     #
# ·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-· #
# Usage:                                                                      #
# $ shask [origin] <message>                                                  #
#                                                                             #
# Arguments                                                                   #
# ---------                                                                   #
# origin                                                                      #
#   Where the question comes from. Must be a valid identifier.                #
# message                                                                     #
#   The logging message.                                                      #
#                                                                             #
# Exit codes                                                                  #
# ----------                                                                  #
# 2                                                                           #
#   - the number of arguments is less than 1 (2 to shlog)                     #
# 1                                                                           #
#   - the origin is not a valid identifier                                    #
###############################################################################

set -euo pipefail

shlog question "$@"
