#!/bin/bash

###############################################################################
# SHERROR                                                                     #
#                                                                             #
# A simple Bash utility to log errors.                                        #
# ·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-· #
# Usage:                                                                      #
# $ sherror [origin] <message>                                                #
#                                                                             #
# Arguments                                                                   #
# ---------                                                                   #
# origin                                                                      #
#   Where the error comes from. Must be a valid identifier.                   #
# message                                                                     #
#   The logging message.                                                      #
#                                                                             #
# Exit codes                                                                  #
# ----------                                                                  #
# 2                                                                           #
#   - the number of arguments is less than 1 (2 to shlog)                     #
# 1                                                                           #
#   - the origin is not a valid identifier                                    #
###############################################################################

set -euo pipefail

shlog error "$@"
