#!/bin/bash

###############################################################################
# SHINFO                                                                      #
#                                                                             #
# A simple Bash utility to log information.                                   #
# ·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-· #
# Usage:                                                                      #
# $ shinfo [origin] <message>                                                 #
#                                                                             #
# Arguments                                                                   #
# ---------                                                                   #
# origin                                                                      #
#   Where the information comes from. Must be a valid identifier.             #
# message                                                                     #
#   The logging message.                                                      #
#                                                                             #
# Exit codes                                                                  #
# ----------                                                                  #
# 2                                                                           #
#   - the number of arguments is less than 1 (2 to shlog)                     #
# 1                                                                           #
#   - the origin is not a valid identifier                                    #
###############################################################################

set -euo pipefail

shlog info "$@"
